[config]
schemaVersion = "0.0.1"

[package]
namespace = "LeKAKiD"
name = "FontPatcher"
description = "Replace in-game font with other things"
websiteUrl = "https://github.com/lekakid/LC-FontPatcher"
containsNsfwContent = false
[package.dependencies]
BepInEx-BepInExPack = "5.4.2100"

[build]
icon = "./icon.png"
readme = "../README.md"
outdir = "./dist"
[[build.copy]]
source = "./bin/Release/net472/FontPatcher.dll"
target = "plugins/"
[[build.copy]]
source = "../LICENSE"
target = "/"
[[build.copy]]
source = "./assets"
target = "config/"

[publish]
repository = "https://thunderstore.io"
communities = [ "lethal-company" ]
[publish.categories]
lethal-company = [ "bepinex", "client-side", "tools", "misc" ]
